backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "src/assets/uploads"
public_folder: "../../assets/uploads"

collections:
  - name: "blog"
    label: "Entradas del blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    editor:
      preview: false
    fields:
      - label: "Titulo"
        name: "title"
        widget: "string"
      - label: "Descripcion"
        name: "description"
        widget: "text"
      - label: "Fecha de publicacion"
        name: "pubDate"
        widget: "datetime"
      - label: "Imagen principal"
        name: "heroImage"
        widget: "image"
        required: false
      - label: "Contenido"
        name: "body"
        widget: "markdown"
